jdbcSettings:
  url: "jdbc:mysql://localhost:3306/appstore?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  username: "dbuser"
  password: "dbuserpass"
  driverClassName: "com.mysql.cj.jdbc.Driver"

packageName: "org.eservice.notice.model"

tableExclusionRules:
  - tableName: [".*_tmp"]
  - tableNames: [".AC_*"]